#ifndef NET_HTTP_FILE_DRIVER_ATOM_H
#define NET_HTTP_FILE_DRIVER_ATOM_H

extern NET_HTTP_FILE_DRIVER_MEDIUM_INIT(atom);
extern NET_HTTP_FILE_DRIVER_MEDIUM_CLOSE(atom);
extern NET_HTTP_FILE_DRIVER_MEDIUM_PULL(atom);


#endif
